// <auto-generated />
using System;
using MarikinAlert.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarikinAlert.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117010419_AddAgencyRelayFeature")]
    partial class AddAgencyRelayFeature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MarikinAlert.Web.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedNodeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedNodeName = "MasterNode",
                            FullName = "",
                            Password = "",
                            PasswordHash = "marikina123",
                            Role = "Dispatcher",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MarikinAlert.Web.Models.AgencyRelay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RelayedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelayedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("RelayedAt");

                    b.HasIndex("ReportId");

                    b.HasIndex("Status");

                    b.HasIndex("ReportId", "AgencyId");

                    b.ToTable("AgencyRelays");
                });

            modelBuilder.Entity("MarikinAlert.Web.Models.ArchivedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArchivedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginalReportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OriginalTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedTimestamp");

                    b.HasIndex("OriginalReportId");

                    b.HasIndex("Status");

                    b.ToTable("ArchivedReports");
                });

            modelBuilder.Entity("MarikinAlert.Web.Models.DisasterReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Category", "Priority");

                    b.HasIndex("Priority", "Timestamp");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MarikinAlert.Web.Models.GovernmentAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyHotline")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlesCategories")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Acronym");

                    b.HasIndex("IsActive");

                    b.ToTable("GovernmentAgencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acronym = "BFP",
                            Address = "BFP National Headquarters, Quezon City",
                            Description = "Philippines national fire fighting agency",
                            Email = "bfp@fire.gov.ph",
                            EmergencyHotline = "116",
                            HandlesCategories = "Fire",
                            IsActive = true,
                            Name = "Bureau of Fire Protection",
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            Acronym = "PNP",
                            Address = "PNP National Headquarters, Camp Crame",
                            Description = "National police force for emergency response",
                            Email = "hotline@pnp.gov.ph",
                            EmergencyHotline = "117",
                            HandlesCategories = "BuildingCollapse,Infrastructure",
                            IsActive = true,
                            Name = "Philippine National Police",
                            Priority = 1
                        },
                        new
                        {
                            Id = 3,
                            Acronym = "PRC",
                            Address = "PRC National Headquarters, Manila",
                            Description = "Emergency medical services and disaster response",
                            Email = "info@redcross.org.ph",
                            EmergencyHotline = "143",
                            HandlesCategories = "Medical",
                            IsActive = true,
                            Name = "Philippine Red Cross",
                            Priority = 1
                        },
                        new
                        {
                            Id = 4,
                            Acronym = "MMDA",
                            Address = "MMDA Main Office, EDSA, Quezon City",
                            Description = "Metro Manila traffic and emergency coordination",
                            Email = "mmda@mmda.gov.ph",
                            EmergencyHotline = "136",
                            HandlesCategories = "Infrastructure,Logistics",
                            IsActive = true,
                            Name = "Metro Manila Development Authority",
                            Priority = 2
                        },
                        new
                        {
                            Id = 5,
                            Acronym = "OCD",
                            Address = "OCD National Headquarters, Quezon City",
                            Description = "National disaster risk reduction and management",
                            Email = "ocd@ocd.gov.ph",
                            EmergencyHotline = "911",
                            HandlesCategories = "Fire,BuildingCollapse,Medical,Logistics,Infrastructure",
                            IsActive = true,
                            Name = "Office of Civil Defense",
                            Priority = 1
                        },
                        new
                        {
                            Id = 6,
                            Acronym = "DPWH",
                            Address = "DPWH Central Office, Port Area, Manila",
                            Description = "Infrastructure and public works emergency response",
                            Email = "info@dpwh.gov.ph",
                            EmergencyHotline = "165-02",
                            HandlesCategories = "Infrastructure,BuildingCollapse",
                            IsActive = true,
                            Name = "Department of Public Works and Highways",
                            Priority = 2
                        },
                        new
                        {
                            Id = 7,
                            Acronym = "CHO",
                            Address = "Marikina City Health Office, Marikina City",
                            Description = "Local health department for medical emergencies",
                            Email = "health@marikina.gov.ph",
                            EmergencyHotline = "8888",
                            HandlesCategories = "Medical",
                            IsActive = true,
                            Name = "City Health Office - Marikina",
                            Priority = 2
                        },
                        new
                        {
                            Id = 8,
                            Acronym = "CEO",
                            Address = "Marikina City Engineering Office, Marikina City",
                            Description = "Local engineering office for infrastructure emergencies",
                            Email = "engineering@marikina.gov.ph",
                            EmergencyHotline = "8888",
                            HandlesCategories = "Infrastructure,BuildingCollapse",
                            IsActive = true,
                            Name = "City Engineering Office - Marikina",
                            Priority = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
